export default BaseGroup;
declare class BaseGroup extends Group {
    constructor(opts: any);
    id: any;
    scope: any;
    top: any;
    left: any;
    width: any;
    height: any;
    resize: any;
    draggable: any;
    group: any;
    dom: any;
    nodes: any[];
    groups: any[];
    options: any;
    __type: string;
    _global: any;
    _on: any;
    _emit: any;
    _container: JQuery<HTMLElement>;
    endpoints: any[];
    _endpointsData: any;
    _isMoving: boolean;
    _isResizing: boolean;
    _init(obj?: {}): void;
    _isInited: boolean;
    _group: any;
    _hasEventListener: boolean;
    draw(obj: any): any;
    addNodes(nodes: any[], isNotEventEmit: any): void;
    addNode(node: any): void;
    removeNodes(nodes: any[], isNotEventEmit: any): any[];
    removeNode(node: any): any[];
    setResize(flat: any, container: any, resizeDom: any): void;
    setSize(width?: any, height?: any): void;
    _moveTo(x: any, y: any): void;
    moveTo(x: any, y: any, isNotEventEmit: any): void;
    getWidth(): any;
    getHeight(): any;
    getEndpoint(pointId: any): any;
    removeEndpoint(pointId: any): any;
    _appendChildren(children?: any[]): void;
    _addEventListener(): void;
    _createEndpoint(isInited: any): void;
    getParentGroup(): this[];
    getSubGroup(): any[];
    addEndpoint(obj: any, isInited: any): any;
    emit(type: any, data: any): void;
    on(type: any, callback: any): void;
    destroy(isNotEventEmit: any): void;
}
import Group from '../interface/group';
