export default BaseEndpoint;
declare class BaseEndpoint extends Endpoint {
    constructor(opts: any);
    id: any;
    options: any;
    orientation: any;
    pos: any;
    type: any;
    nodeType: any;
    nodeId: any;
    root: any;
    scope: any;
    expandArea: any;
    limitNum: any;
    connectedNum: number;
    __type: string;
    _node: any;
    _global: any;
    _on: any;
    _emit: any;
    _top: number;
    _left: number;
    _posTop: number;
    _posLeft: number;
    _width: number;
    _height: number;
    _linkable: boolean;
    _coordinateService: any;
    dom: any;
    _isInitedDom: boolean;
    _init(obj: any): void;
    draw(obj: any): any;
    updatePos(dom?: any, orientation?: any, pos?: any): void;
    _getGroupPos(group: any): {
        top: number;
        left: number;
    };
    hasConnection(): boolean;
    moveTo(x: any, y: any): void;
    linkable(): void;
    unLinkable(): void;
    hoverLinkable(): void;
    unHoverLinkable(): void;
    attachEvent(): void;
    emit(type: any, data: any): void;
    on(type: any, callback: any): void;
    destroy(isNotEvent: any): void;
}
import Endpoint from '../interface/endpoint';
