export default BaseNode;
declare class BaseNode extends Node {
    constructor(opts: any);
    id: any;
    scope: any;
    group: any;
    top: any;
    left: any;
    dom: any;
    draggable: any;
    options: any;
    __type: string;
    _on: any;
    _emit: any;
    _global: any;
    endpoints: any[];
    _endpointsData: any;
    _endpointLimitNum: any;
    _isMoving: boolean;
    width: number;
    height: number;
    _isForceUpdateSize: boolean;
    draw(obj: any): any;
    addEndpoint(obj: any, isInited: any): any;
    removeEndpoint(pointId: any): any;
    getEndpoint(pointId: any, type: any): any;
    _init(obj?: {}): void;
    _group: any;
    _isInited: boolean;
    _hasEventListener: boolean;
    _moveTo(x: any, y: any): void;
    moveTo(x: any, y: any, isNotEventEmit: any): void;
    getWidth(useCache: any): number;
    getHeight(useCache: any): number;
    _createEndpoint(isInited: any): void;
    _addEventListener(): void;
    setDraggable(draggable: any): void;
    emit(type: any, data: any): void;
    on(type: any, callback: any): void;
    destroy(isNotEvent: any): void;
}
import Node from '../interface/node';
