export default Canvas;
declare class Canvas extends EventEmit3<string | symbol, any> {
    constructor();
    draw(): void;
    getNode(): void;
    getEdge(): void;
    getGroup(): void;
    addNode(): void;
    addNodes(): void;
    addEdge(): void;
    addEdges(): void;
    addGroups(): void;
    removeNode(): void;
    removeNodes(): void;
    removeEdge(): void;
    removeEdges(): void;
    removeGroup(): void;
    getNeighborEdges(): void;
    getNeighborNodes(): void;
    getNeighborNodesAndEdgesByLevel(): void;
    getAdjcentTable(): void;
    getZoom(): void;
    setZoomable(): void;
    zoom(): void;
    getOffset(): void;
    setMoveable(): void;
    move(): void;
    getOrigin(): void;
    setOrigin(): void;
    getDataMap(): void;
    setGirdMode(): void;
    setGuideLine(): void;
    justifyCoordinate(): void;
    setSelectMode(): void;
    getUnion(): void;
    getAllUnion(): void;
    add2Union(): void;
    removeUnion(): void;
    removeAllUnion(): void;
    focusNodeWithAnimate(): void;
    focusNodesWithAnimate(): void;
    canvas2terminal(): void;
    terminal2canvas(): void;
    save2img(): void;
    updateRootResize(): void;
    click(): void;
    doubleClick(): void;
    onContextmenu(): void;
}
import EventEmit3 = require("eventemitter3");
